config/routes.rb
WooDo::Application.routes.draw do

    resources :users, only: [:new, :create, :edit, :update, :show, :update]
    resources :sessions, only: [:new, :create, :destroy]
    resources :tasks do
      post :reorder, :on => :collection
    end
    resources :relationships

    resources :lists, only: [:create, :show, :destroy, :edit, :update] do
      post :share
    end

    get "static_pages/home"

   

    root to: "static_pages#home"

    match '/signin', to: "sessions#new"
    match '/signout', to: "sessions#destroy"
    match '/signup', to: "users#new"

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
				<div class="container">
						<a class="brand" href="/" style="font-size: 50px;margin: 5px;">Woo Do</a>
						<div class="nav pull-right">
						<% if signed_in? %>
								<li id="fat-menu" class="dropdown">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= gravatar_for current_user, size: 30 %><%= current_user.name %></a>
										<ul class="dropdown-menu">
												<li><%= link_to "Profile", current_user %></li>
												<li><%= link_to "Settings", edit_user_path(current_user) %></li>
												<li class="divider"></li>
												<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
										</ul>
								</li>
						<% else %>
								<a href="<%= signin_path %>" type="button" class="btn btn-primary">Sign in</a> 
						<% end %>
						</div>
				</div>
		</div>
</div>

app/views/layouts/_list.html.erb
<%= javascript_include_tag "custom" %>
<script type="text/javascript">
$(document).ready(function(){


	window.Task = Backbone.Model.extend({
		toggleTaskStatus: function(){
			this.set({completed : !this.get('completed')});
			this.save();
		}
	});

	window.Tasks = Backbone.Collection.extend({
		model: Task,
		url: '/tasks',
		comparator: function(model) {
        return model.get('ordinal');
    }
	});

	window.List = Backbone.Model.extend({
		initialize: function(){
			this.tasks = new Tasks(this.get('tasks'));
		},
		toggleListStatus: function(){
			var toggled = !this.get('completed');
			this.set({completed: toggled});
			this.tasks.forEach(function(task){
				task.set({completed: toggled});
				task.save();
			},this);
			this.save();
		}
	});

	window.Lists = Backbone.Collection.extend({
		model: List,
		url: '/lists'
	});


	window.lists_collection = new Lists();
	lists_collection.reset(<%= @lists.to_json(:include => :tasks ).html_safe %>);


	window.TaskView = Backbone.View.extend({
		tagName: 'li',
		initialize: function(){
			this.model.on('change',this.render,this);
		},
		template: _.template($('#task-template').html()),
		events: {
			'change input': 'toggleTaskStatus',
			'click #task-delete': 'deleteTask',
			'drop' : 'drop'
		},
		drop: function(event, index) {
      this.$el.trigger('update-sort', [this.model, index]);
    },
		deleteTask: function(){
			this.model.destroy();
		},
		toggleTaskStatus: function(){
			this.model.toggleTaskStatus();
		},
		render: function(){
			var className;
			if(this.model.get('completed')){
				this.$el.removeClass('incomplete');
				className = 'complete';
			}
			else{
				this.$el.removeClass('complete');
				className = 'incomplete';
			}
			this.$el.addClass(className).html(this.template(this.model.toJSON()));
			return this;
		}
	});

	window.TasksView = Backbone.View.extend({
		tagName: 'ul',
		id: 'tasks',
		events: {
			'update-sort': 'updateSort'
		},
		updateSort: function(event, model, position) {            
        this.collection.remove(model);

        this.collection.each(function (model, index) {
            var ordinal = index;
            if (index >= position)
                ordinal += 1;
            model.set('ordinal', ordinal);
        });            

        model.set('ordinal', position);
        this.collection.add(model, {at: position});

        // to update ordinals on server:
        var ids = this.collection.pluck('id');
        console.log(ids);
        $.ajax({
        	url: "/tasks/reorder",
        	method: "POST",
        	data: {ids: ids}
        })
        //$('#post-data').html('post ids to server: ' + ids.join(', '));

        this.render();
    },
		initialize: function(){
			this.collection.on('destroy',this.render,this);
		},
		render: function(){
			this.$el.html('');
			this.addAll();
			return this;
		},
		addAll:function(){
			this.collection.forEach(this.addOne,this);
		},
		addOne: function(task){
			var task_view = new TaskView({model: task});
			this.$el.append(task_view.render().el);
		}
	});

	window.ListView = Backbone.View.extend({
		initialize: function(){
			this.model.on('change',this.render,this);
		},
		template: _.template($('#list-template').html()),
		events: {
			'click #list-delete': 'deleteList',
			'click #list-toogle': 'toggleListStatus'
		},
		toggleListStatus: function(){
			this.model.toggleListStatus();
		},
		deleteList: function(){
			this.model.destroy();
		},
		render: function(){
			var tasks_view = new TasksView({collection: this.model.tasks});
			this.$el.html(this.template(this.model.toJSON()));
			this.$el.find('.list-body').html(tasks_view.render().el);
			return this;
		}
	});

	window.ListsView = Backbone.View.extend({
		tagName: 'li',
		el: $('#lists'),
		class: 'span4 list-container',
		collection: lists_collection,
		initialize: function(){
			this.collection.on('add',this.addOne,this);
			this.collection.on('reset',this.render,this);
			this.collection.on('destroy',this.render,this);
		},
		render: function(){
			this.$el.html("");
			this.addAll();
		},
		addAll: function(){
			this.collection.forEach(this.addOne,this);
		},
		addOne: function(list){
			var list_view = new ListView({model: list});
			this.$el.append(list_view.render().el);
		}
	});

	window.lists_view = new ListsView();
	lists_view.render();
	//console.log(lists_view.el);

	$('.list-body #tasks').sortable({
		stop: function(event, ui) {
      ui.item.trigger('drop', ui.item.index());
    }
	});
	$('.list-body #tasks').disableSelection();

});
</script>
<ol class="row" id="lists">
    <% if @user.lists.any? %>
        <%= render @lists %>
    <% end %>
</ol>

app/views/layouts/_task_form.html.erb
<div class="row">
    <div id="show-error"> </div>
    <%= form_for @task, :remote => true, :html => { :class => "form-inline task-creator" } do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="input-append">
            <%= f.text_field :content, class: "input-xlarge"  %>
            <%= f.submit "Create", class: "btn btn-primary"  %>
            </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Woo Do | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render "layouts/header" %> 
    <div class="container center">
        <%= render 'shared/flash_messages' %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
    </div
</body>
</html>

app/views/layouts/sample.js.erb
alert("Hey")